import Header from '@/components/Header';
import Footer from '@/components/Footer';
import LaunchBand from '@/components/LaunchBand';

const sections = [
  ['overview','Overview'],['start','Starting a launch'],['details','What you’ll be asked'],['review','Review & edit'],['confirm','Confirmation'],['commands','Commands'],['wallet','Creator wallet'],['network','Network'],['status','After launch'],['support','Support']
];

export default function DocsPage(){
  return <main className="subpage"><Header/><section className="subpageHero"><span className="eyebrow pillEyebrow">PRODUCT GUIDE</span><h1>Launch/SMS docs.</h1><p>Everything you need to know about starting, reviewing, editing and confirming a token launch from Messages.</p></section><div className="docsLayout"><aside className="docsNav">{sections.map(([id,label])=><a href={`#${id}`} key={id}>{label}</a>)}</aside><article className="docsContent">
    <section className="docsSection" id="overview"><h2>Overview</h2><p>Launch/SMS is a guided launch experience inside Messages. You start with one word, answer the prompts in order, review the final token details, and choose when to confirm.</p><div className="docCallout">The thread is designed to stay simple: one question at a time, one final review, one explicit confirmation.</div></section>
    <section className="docsSection" id="start"><h2>Starting a launch</h2><p>Open Messages and send <strong>LAUNCH</strong> to the Launch/SMS number shown on the site. If there is no active launch in your thread, the first token prompt appears immediately.</p><h3>Returning to an unfinished launch</h3><p>Active launch sessions keep their current step for a limited period. Continue by answering the prompt already waiting in the thread.</p></section>
    <section className="docsSection" id="details"><h2>What you’ll be asked</h2><p>The guided flow collects the information needed to prepare the token:</p><ul><li>Token name</li><li>Ticker</li><li>Short description</li><li>Logo URL or IPFS URI</li><li>Optional website and social links</li><li>Creator fee wallet</li><li>Creator tax and buyback preference</li></ul><p>Optional links can be skipped. Required fields are checked before the flow moves on.</p></section>
    <section className="docsSection" id="review"><h2>Review & edit</h2><p>After the last prompt, Launch/SMS sends a compact review containing the token name, ticker, description, creator wallet and selected launch settings.</p><p>If something is wrong, reply <strong>BACK</strong> to return to the previous step. Nothing is submitted simply because you reached the review.</p></section>
    <section className="docsSection" id="confirm"><h2>Confirmation</h2><p>A launch only continues after an explicit confirmation. Reply <strong>CONFIRM</strong> when the review is correct.</p><div className="docCallout">Treat CONFIRM as the final action in the launch flow. Review the wallet, ticker and launch settings carefully first.</div></section>
    <section className="docsSection" id="commands"><h2>Commands</h2><div className="commandTable"><div className="commandRow"><code>LAUNCH</code><span>Start a new launch when no active session exists.</span></div><div className="commandRow"><code>BACK</code><span>Move back one prompt to edit the previous answer.</span></div><div className="commandRow"><code>CONFIRM</code><span>Confirm the final reviewed launch.</span></div><div className="commandRow"><code>CANCEL</code><span>Stop the active launch session.</span></div></div></section>
    <section className="docsSection" id="wallet"><h2>Creator wallet</h2><p>The flow asks for an EVM wallet address to use as the creator fee recipient. The address must be a valid <code>0x…</code> address. Always verify the full address before confirmation.</p></section>
    <section className="docsSection" id="network"><h2>Network</h2><p>Launch/SMS is designed for token launches on Robinhood Chain using Pons. The customer experience stays in Messages; the final token and explorer links are returned to the thread after a successful launch.</p></section>
    <section className="docsSection" id="status"><h2>After launch</h2><p>When a launch completes, the thread returns the token address and links you can use to inspect the token and transaction. Save the token address; it is the canonical identifier for the launched token.</p></section>
    <section className="docsSection" id="support"><h2>Support</h2><p>If a launch stops before completion, do not repeatedly confirm the same launch. Review the message returned in the thread, correct the requested field when possible, or cancel and start again.</p></section>
  </article></div><LaunchBand/><Footer/></main>
}
